Home/urls.py
from django.conf.urls import include, url
from . import views


app_name='Home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^product/(?P<cat_name>\w+)/$', views.product, name='product'),
    url(r'^detail/([\w ]+)/$', views.detail, name='detail'),
    url(r'^cart/$', views.cart, name='cart'),

]

peddle/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^home/',include('Home.urls', namespace="Home") ),
    url(r'^$',include('Home.urls') ),
]

Home/models.py
from django.db import models

class Catagory(models.Model):
	name = models.CharField(max_length=250)

	def __str__(self):
		return self.name

class Product(models.Model):
	catagory = models.ForeignKey(Catagory, on_delete=models.CASCADE)
	name = models.CharField(max_length=250)
	price = models.CharField(max_length=250)
	img = models.CharField(max_length=1000)

	def __str__(self):
		return self.name

class Offer(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	discount= models.IntegerField(default=0)

	def __str__(self):
		return self.product.name

#class Cart(models.Model):

Home/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Catagory, Offer, Product
from django.shortcuts import render
from django.db.models import Q
import operator


def index(request):
	all_cats=Catagory.objects.all()
	top_deals=Offer.objects.order_by('-discount')[:4]


	context={
		'all_cats': all_cats,
		'top_deals': top_deals
	}
	
	return render(request, 'Home/index.html', context)


# def detail(request, cat_id):
# 	catagory=get_object_or_404(Catagory, pk=cat_id)
# 	return render(request, 'Home/detail.html', { 'catagory' : catagory })

def about(request):
	context={}
	return render(request, 'Home/about.html', context)
def contact(request):
	context={}
	return render(request, 'Home/contact.html', context)
def product(request, cat_name):
	all_cats=Catagory.objects.all()
	# print(cat_name)
	if cat_name == "all":
		prods=Product.objects.all()
	else:
		prods=Product.objects.filter(catagory__name=cat_name)

	context={
		'all_cats' : all_cats,
		'prods' : prods,
	}
	return render(request, 'Home/product.html', context)
def detail(request, prod_name):
	product=Product.objects.filter(name=prod_name)
	cat_prod=product.values('catagory')
	prods=Product.objects.filter(catagory__pk=cat_prod)
	if(len(prods) >4):
		prods=prods[:4]

	context={
		'product' : product[0],
		'cat_prod' : cat_prod,
		'prods' : prods,
	}
	return render(request, 'Home/detail.html', context)
def cart(request):
	context={}
	return render(request, 'Home/cart.html', context)

Home/templates/Home/about.html
{% extends 'Home/base.html' %}
{% load staticfiles %}
{% block title %}About{% endblock %}
{% block activeAbout %}active{%endblock%}
{% block body %}
	<br><br><br><br><br><br>
	
	<div class="container marketing">
		<center><h1>About</h1></center>
		<hr>
		<br>
	  <div class="row">
	    <div class="col-lg-4">
	      <img class="img-circle" src="{% static 'Home/images/profile.jpg' %}" alt="Generic placeholder image" width="200">
	      <h2>Mayank Mohindra</h2>
	      <p>
<pre>
Undergrad, IIIT-Delhi
Developer and Designer
Find me on GitHub:
<a href="https://github.com/mayankmtg">https://github.com/mayankmtg</a>
</pre>
	      
	      </p>
	      <p><a class="btn btn-default" href="#" role="button">View Full Profile &raquo;</a></p>
	    </div>
	    	<!-- /.col-lg-4 -->
	    <div class="col-lg-8" style="border-style: outset;border-radius: 40px;">
	      <h2>Peddle</h2>
	      <hr>
	      <p style="font-size: 18px;">
	      Peddle is a completely funstional dynamic e-commerce website that is highly customisable and useable by any person regardless of their background.
	      <br>
	      You can use the admin interface to add more products and delete them in any case. You can also use them to add discounts to the products and remove them whenever needed.
	      <br>
	      The home page displays the products with the best deals only and no other.
	      </p>
	      <br><br><br><br>
	    </div><!-- /.col-lg-4 -->
	    
	  </div><!-- /.row -->
	</div>
{% endblock %}

Home/templates/Home/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    

	<title>Peddle-{% block title %}{% endblock %}</title>

	<!-- Bootstrap core CSS -->
    {% load staticfiles %}
    <!-- Latest compiled and minified CSS -->
    <link href="{% static 'Home/css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'Home/css/portfolio-item.css' %}" rel="stylesheet">
    <link href="{% static 'Home/css/1-col-portfolio.css' %}" rel="stylesheet">

    <link rel="icon" href="#">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <link href="{% static 'Home/css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'Home/css/portfolio-item.css' %}" rel="stylesheet">
    <link href="{% static 'Home/css/1-col-portfolio.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">Peddle</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="{% block activeHome %}{%endblock%}"><a href="{% url 'Home:index' %}">Home</a></li>
            <li class="{% block activeAbout %}{%endblock%}"><a href="{% url 'Home:about' %}">About</a></li>
            <li class="{% block activeContact %}{%endblock%}"><a href="{% url 'Home:contact' %}">Contact</a></li>
            <li class="{% block activeProduct %}{%endblock%}"><a href="{% url 'Home:product' 'all' %}">View Products</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'Home:cart' %}"><span class="glyphicon glyphicon-shopping-cart {% block activeCart %}{% endblock %}"></span> Cart</a></li>
            <li><a href="./"><span class="glyphicon glyphicon-log-in"></span> Log In<span class="sr-only">(current)</span></a></li>
          </ul>
          <form class="navbar-form navbar-right" role="search" method="get" action="#">
            <div class="form-group">
              <input type="text" placeholder="Search" class="form-control">
            </div>
            <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span> Search</button>
          </form>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    

    {% block body %}
    {% endblock %}


	
    <div class="container marketing">
    <hr>
      <!-- FOOTER -->
      <footer>
        <p class="pull-right"><a href="#myCarousel">Back to top</a></p>
        <p>&copy; 2017 Peddle, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>

    </div><!-- /.container -->


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>
      window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')
    </script>

    <script src="{% static 'Home/js/bootstrap.min.js' %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'Home/js/holder.min.js' %}"></script>
    <script type="text/javascript">
        // Select all links with hashes
        $('a[href*="#"]')
          // Remove links that don't actually link to anything
          .not('[href="#"]')
          .not('[href="#0"]')
          .click(function(event) {
            // On-page links
            if (
              location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') 
              && 
              location.hostname == this.hostname
            ) {
              // Figure out element to scroll to
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
              // Does a scroll target exist?
              if (target.length) {
                // Only prevent default if animation is actually gonna happen
                event.preventDefault();
                $('html, body').animate({
                  scrollTop: target.offset().top
                }, 1000, function() {
                  // Callback after animation
                  // Must change focus!
                  var $target = $(target);
                  $target.focus();
                  if ($target.is(":focus")) { // Checking if the target was focused
                    return false;
                  } else {
                    $target.attr('tabindex','-1'); // Adding tabindex for elements not focusable
                    $target.focus(); // Set focus again
                  };
                });
              }
            }
          });
    </script>
</body>
</html>

Home/templates/Home/cart.html
{% extends 'Home/base.html' %}
{% load staticfiles %}
{% block title %}title here{% endblock %}
{% block body %}
    <br><br><br>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Page Heading
                    <small>Secondary Text</small>
                </h1>
            </div>
        </div>
        <!--loop starts here-->
        <div class="row">
            <div class="col-md-7">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/700x300" alt="">
                </a>
            </div>
            <div class="col-md-5">
                <h3>Product One</h3>
                <h4>Subheading</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium veniam exercitationem expedita laborum at voluptate. Labore, voluptates totam at aut nemo deserunt rem magni pariatur quos perspiciatis atque eveniet unde.</p>
                <a class="btn btn-primary" href="#">View Product <span class="glyphicon glyphicon-chevron-right"></span></a>
            </div>
        </div>
        <!--loop ends here-->

        <hr>

    </div>
    <!-- /.container -->
{% endblock %}

Home/templates/Home/contact.html
{% extends 'Home/base.html' %}
{% load staticfiles %}
{% block title %}Contact{% endblock %}
{% block activeContact %}active{%endblock%}
{% block body %}

	<div class="container marketing">
	
	<hr class="featurette-divider" style="display: none;">
	<center>
		<h1 class="featurette-heading">Contact Us</h1>
		<p class="lead">We are listening</p>
	</center>
      <hr>

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Reach/Call/Mail<span class="text-muted">Us</span></h2>
          <p class="lead">+91-9958306474</p>
          <p class="lead">IIIT-Delhi</p>
          <p class="lead">mayank15056@iiitd.ac.in</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

    </div><!-- /.container -->
{% endblock %}

Home/templates/Home/detail.html
{% extends 'Home/base.html' %}
{% load staticfiles %}
{% block title %}title here{% endblock %}
{% block body %}
    <br><br><br>
    <div class="container">

        <!-- Portfolio Item Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{{ product.name }}
                    <small>{{ product.catagory.name }}</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Portfolio Item Row -->
        <div class="row">

            <div class="col-md-8">
                <img class="img-responsive" src="{% static 'Home/images/Products/' %}{{ product.img }}" alt="" style="height: 500px;">
            </div>

            <div class="col-md-4">
                <h3>Product Description</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
                <h3>₹{{ product.price }}/-</h3>
                <br>
                <a class="btn btn-lg btn-warning" href="#">Add To Cart</span></a>
                <h3>Product Details</h3>
                <ul>
                    <li>Lorem Ipsum</li>
                    <li>Dolor Sit Amet</li>
                    <li>Consectetur</li>
                    <li>Adipiscing Elit</li>
                </ul>
            </div>

        </div>
        <!-- /.row -->

        <!-- Related Projects Row -->
        <div class="row">

            <div class="col-lg-12">
                <h3 class="page-header">Related Products</h3>
            </div>
            {% for prod in prods %}
            <div class="col-sm-3 col-xs-6">
                <a href="{% url 'Home:detail' prod.name %}">
                    <img class="img-responsive portfolio-item" src="{% static 'Home/images/Products/' %}{{ prod.img }}" alt="" style="height: 200px;">
                </a>
            </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}

Home/templates/Home/index.html
{% extends 'Home/base.html' %}
{% load staticfiles %}
{% block title %}Home{% endblock %}
{% block activeHome %}active{%endblock%}
{% block body %}
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    
    <div class="carousel-inner" role="listbox">
      
      <div class="item active">
        <img class="first-slide" src="{% static 'Home/images/slider1.jpg' %}" style="opacity: 0.5;" alt="First slide">
        <div class="container">
          <div class="carousel-caption">
            <h1>Start Peddling</h1>
            <p>It looks like you are in need of a change. It looks like you want something better. It looks like you are in search for the Latest and Best Quality Products, then</p>
            <p><a class="btn btn-lg btn-primary" href="#topDeals" role="button">Start Today</a></p>
          </div>
        </div>
      </div>

      <div class="item">
        <img class="second-slide" src="{% static 'Home/images/slider2.jpg'%}" style="opacity: 0.5;" alt="Second slide">
        <div class="container">
          <div class="carousel-caption">
            <h1>Top Deals and Exciting Offers</h1>
            <p>We continue to provide top Deals and exciting offers to our Customers. The Deals are changing on a daily basis so Stay Tuned!!</p>
            <p><a class="btn btn-lg btn-primary" href="#topDeals" role="button">View Top Deals</a></p>
          </div>
        </div>
      </div>
      
      <div class="item">
        <img class="third-slide" src="{% static 'Home/images/slider4.jpg'%}" style="opacity: 0.5;" alt="Third slide">
        <div class="container">
          <div class="carousel-caption">
            <h1>Browse Our Exciting Range</h1>
            <p>Browse through our latest Collection, all 50,000,000,000 products, which provide the best user experience.</p>
            <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse Products</a></p>
          </div>
        </div>
      </div>
    
    </div>
    
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>

  </div><!-- /.carousel -->

  <div class="container">
      <div class="row">
          <div class="col-lg-12">
              <h1 id="topDeals">&nbsp;</h1>
              <h1 class="page-header">Top Deals</h1>
          </div>
          
          {% for item in top_deals %}
          <div class="col-lg-3 col-md-4 col-xs-6 thumb">
              <a class="thumbnail" href="{% url 'Home:detail' item.product.name %}" style="text-decoration: none;">
                  <img class="img-responsive" style="height: 200px;" src="{% static 'Home/images/Products' %}/{{ item.product.img }}" alt="">
                  <center>{{ item.product.name }}<br>{{ item.discount }}% OFF</center>
              </a>
          </div>
          {% endfor %}

          <p><a class="btn btn-default" href="#" role="button">View More &raquo;</a></p>
      </div>
  </div>

{% endblock %}

Home/templates/Home/product.html
{% extends 'Home/base.html' %}
{% load staticfiles %}
{% block title %}Products{% endblock %}
{% block activeProduct %}active{%endblock%}
{% block body %}
<br><br><br><br>
	<div class="container">

        <div class="row">

            <div class="col-md-3">
                <p class="lead">Catagories</p>
                <div class="list-group">
                    <a href="{% url 'Home:product' 'all' %}" class="list-group-item"><b><i>All</i></b></a>
                    {% for cats in all_cats %}
                    <a href="{% url 'Home:product' cats.name %}" class="list-group-item">{{ cats.name }}</a>
                    {% endfor %}
                </div>
            </div>

            <div class="col-md-9">
                <div class="row">
                	{% for prod in prods %}
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="{% static 'Home/images/Products/' %}{{ prod.img }}" alt="" style="height: 150px;">
                            <div class="caption">
                                <h4 class="pull-right">₹{{ prod.price }}</h4>
                                <h4><a href="{% url 'Home:detail' prod.name %}">{{ prod.name }}</a>
                                </h4>
                                <p>General Description</p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">15 reviews</p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                </p>
                            </div>
                        </div>
                    </div>	
                    {% endfor %}
                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->

{% endblock %}